config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  resources :items, only: [:show, :index, :new, :create]
  resources :categories, except: [:destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
    has_many :item_categories
    has_many :items,  through: :item_categories
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :stock, optional: true
	accepts_nested_attributes_for :stock
	
	

	
	has_many :item_categories
    has_many :categories, through: :item_categories 
	validates :title, presence: true
	validates :description, presence: true
	
end

app/models/item_category.rb
class ItemCategory < ApplicationRecord

belongs_to :item
belongs_to :category 
end	

app/models/stock.rb
class Stock < ApplicationRecord
	has_one :item
	validates :price, presence: true
	validates :quantity, presence: true
	
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def new
		@category =  Category.new

	end

	def index
		@categories = Category.all

	end	

	def show
		@category = Category.find(params[:id])
		@items = @category.items


	end

	def create
		
	end
	    
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def show 
		@item = Item.find(params[:id])	
	end

	def index

		@items = Item.all
	end
	def new 
		@item = Item.new
		@item.build_stock
		

	end
	
	def create
		@item = Item.new(item_params)
  
	    if @item.save
				flash.now[:alert] = "Item was created successfully."
				redirect_to @item
			else
				flash.now[:alert] = "Item was not created."
			end
	end
	def item_params
		params.require(:item).permit(:title, :description,:image,:user_id,category_ids: [],stock_attributes: [:price, :quantity]).merge(user: current_user)    
	end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @users = User.all
  end
  def new
    @item = USer.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/index.html.erb
<div id="page-content">
<h1 class="text-center">All Categories</h1>
<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(category.items.count, "item") %></p>
          </div>
          
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/categories/show.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>
<h3 class="text-center mt-4">Items</h3>
<%= render 'items/item' %>
</div>
<div class="mt-0 text-center">
    <%= link_to 'Back To categories', categories_path, class: "btn btn-outline-primary text-dark" %>
</div>

app/views/items/_item.html.erb
<div class="card-block top-buffer">
  <div class="row ">
      <% @items.each do |item| %>
            <div class="card border-danger" style="width: 20rem;">
              <%= image_tag item.image, height: 250 %>
              <div class="card-body">
                <h5 class="card-title"><%= link_to item.title, item_path(item), class: "text-success" %></h5>
                <p class="card-text">{{item.description}}</p>
              </div>
            </div>
      <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div id="page-content">

<%= render 'items/item' %>
</div>

app/views/items/new.html.erb
<h3 class="container">Create new item</h3>
 <div class="row justify-content-md-center">
  <div class="col-10">

     <%= form_for @item do |f| %>  
        <div class="form-group row">
          <%= f.label :title, class: "col-6 col-form-label text-dark" %>
          <div class="col-7">
            <%= f.text_field :title, class: "form-control shadow rounded"%>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-6 col-form-label text-dark" %>
          <div class="col-7">
            <%= f.text_area :description, class: "form-control-file form-control shadow rounded" %>
          </div>
        </div>

          <div class="form-group row">
          <%= f.label :image, class: "col-6 col-form-label text-dark" %>
          <div class="col-7">
            <%= f.text_field :image, class: "form-control shadow rounded"%>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :category, class: "col-6 col-form-label text-dark" %>
          <div class="col-7"> 
            <%= f.collection_select(:category_ids, Category.all, :id, :name, 
            {:prompt => "Make your selection from the list below (can be empty)"}, {:multiple => true, size: 3, class: "custom-select shadow rounded"}) %>

          </div>
        </div>


       


        <%= f.fields_for :stock do |a| %>

          <div class="form-group row">
            <%=a.label :price, class: "col-6 col-form-label text-dark"  %>
            <div class="col-7"> 
              <%= a.text_field :price, rows: 10, class: "form-control shadow rounded" %>
            </div>  
          </div>
          <div class="form-group row">
            <%=a.label :quantity, class: "col-6 col-form-label text-dark"  %>
            <div class="col-7"> 
              <%= a.text_field :quantity, rows: 10, class: "form-control shadow rounded" %>
            </div>  
          </div>

      
        <% end %>  
        
        

        <div class="form-group">
          <%= f.submit "create item", class: "btn btn-outline-dark btn-lg" %>
        </div>
    <%end%>
  </div>
   
 </div>    

  

app/views/items/show.html.erb
<div id="page-content">
	<div class="mt-0 text-center">
      <%= link_to 'Back To Items', items_path, class: "btn btn-outline-primary text-dark" %>
    </div>	  
    <div class="row justify-content-md-center">
		<div class="col-16">
			<div class="card" style="width: 18rem;">
                <%= image_tag @item.image, height: 250 %>
				<div class="card-body">
					<h5 class="card-title"><%= @item.title %></h5>
						<p class="card-text"><%= @item.description %></p>
				</div>
				<ul class="list-group list-group-flush">
					<li class="list-group-item">Price :<%= @item.stock.price %></li>
					<li class="list-group-item">Quantity:<%= @item.stock.quantity %></li>
				</ul>
								  
			</div>

				<li class="card-header">Owned by:<%= link_to @item.user.email  %> </li>
		</div>
		</div>
	</div>	
					
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark py-2">
  <%= link_to 'E-KART', root_path, class: "navbar-brand" %> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item active">
        <%= link_to 'Categories', categories_path, class: "nav-link" %>
      </li>
    
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <% if current_user %> 
      <li class="nav-item" >
            <%= link_to 'Add Item',new_item_path(@user),type:"button", class:"btn btn-primary" %>
      </li> 
      
        <li class="nav-item">
          <%= link_to 'LOGOUT',  destroy_user_session_path, class: "btn btn-danger ", method: :delete %>
        </li>
    <% else %>  
        <li class="nav-item">
          <%= link_to 'LOGIN', new_user_session_path, class: "btn btn-success " %>
        </li>
    <% end %>  
       

      

    </form>
    
  
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
 
    

  </body>
</html>

app/views/welcome/index.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center text-black",style="background-image: url(http://www.californiafootgolfclub.com/static/img/footgolf-1.jpg); background-size: 100%;">
      <h1 class="display-4">E-KART</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-success" %>

    </div>


  </div>
</div>